ROLES_DB = [

    # Data & Analytics
    "data analyst",
    "senior data analyst",
    "junior data analyst",
    "data scientist",
    "senior data scientist",
    "junior data scientist",
    "data engineer",
    "senior data engineer",
    "junior data engineer",
    "analytics engineer",
    "business analyst",
    "business intelligence analyst",
    "bi analyst",
    "bi developer",
    "bi engineer",
    "power bi developer",
    "power bi analyst",
    "tableau developer",
    "tableau analyst",
    "reporting analyst",
    "insights analyst",
    "research analyst",
    "quantitative analyst",
    "financial analyst",
    "marketing analyst",
    "product analyst",
    "operations analyst",
    "supply chain analyst",
    "hr analyst",
    "people analyst",
    "clinical data analyst",
    "healthcare analyst",

    # Machine Learning & AI
    "machine learning engineer",
    "ml engineer",
    "ai engineer",
    "artificial intelligence engineer",
    "deep learning engineer",
    "nlp engineer",
    "computer vision engineer",
    "mlops engineer",
    "research scientist",
    "applied scientist",
    "ai researcher",
    "data modeler",

    # Software & Development
    "python developer",
    "python engineer",
    "software engineer",
    "software developer",
    "backend developer",
    "backend engineer",
    "frontend developer",
    "frontend engineer",
    "fullstack developer",
    "fullstack engineer",
    "web developer",
    "web engineer",
    "java developer",
    "javascript developer",
    "react developer",
    "node developer",
    "django developer",
    "flask developer",
    "api developer",
    "cloud engineer",
    "devops engineer",
    "site reliability engineer",
    "platform engineer",
    "database administrator",
    "database developer",
    "etl developer",
    "sql developer",

    # Management & Leadership
    "data manager",
    "analytics manager",
    "engineering manager",
    "product manager",
    "project manager",
    "program manager",
    "scrum master",
    "tech lead",
    "team lead",

    # Entry Level / Intern
    "data analyst intern",
    "data science intern",
    "software engineering intern",
    "ml intern",
    "business analyst intern",
    "data engineering intern",
    "analyst trainee",
    "associate data analyst",
    "associate data scientist",
    "graduate analyst",
]