SKILLS_DB = [

    # Programming Languages
    "python",
    "r",
    "sql",
    "java",
    "javascript",
    "typescript",
    "scala",
    "c++",
    "c#",
    "go",
    "bash",
    "shell scripting",
    "pyspark",
    "spark",

    # Data Analysis & Manipulation
    "pandas",
    "numpy",
    "dask",
    "polars",
    "data analysis",
    "data wrangling",
    "data cleaning",
    "data preprocessing",
    "feature engineering",
    "exploratory data analysis",
    "eda",
    "etl",
    "data pipeline",
    "data modeling",

    # Visualization & BI
    "power bi",
    "tableau",
    "excel",
    "advanced excel",
    "pivot tables",
    "matplotlib",
    "seaborn",
    "plotly",
    "dash",
    "looker",
    "metabase",
    "superset",
    "google data studio",
    "qlik",
    "d3.js",

    # Machine Learning
    "machine learning",
    "deep learning",
    "scikit-learn",
    "tensorflow",
    "keras",
    "pytorch",
    "xgboost",
    "lightgbm",
    "catboost",
    "random forest",
    "gradient boosting",
    "neural networks",
    "natural language processing",
    "nlp",
    "computer vision",
    "opencv",
    "transformers",
    "hugging face",
    "bert",
    "gpt",
    "llm",
    "reinforcement learning",
    "time series",
    "forecasting",

    # Statistics & Math
    "statistics",
    "statistical analysis",
    "hypothesis testing",
    "a/b testing",
    "regression",
    "linear regression",
    "logistic regression",
    "classification",
    "clustering",
    "k-means",
    "pca",
    "dimensionality reduction",
    "probability",
    "bayesian",
    "descriptive statistics",
    "inferential statistics",

    # Databases & Querying
    "mysql",
    "postgresql",
    "sqlite",
    "mongodb",
    "redis",
    "cassandra",
    "oracle",
    "ms sql server",
    "bigquery",
    "snowflake",
    "redshift",
    "databricks",
    "hive",
    "nosql",

    # Cloud & Infrastructure
    "aws",
    "azure",
    "google cloud",
    "gcp",
    "s3",
    "ec2",
    "lambda",
    "airflow",
    "apache airflow",
    "kafka",
    "spark",
    "hadoop",
    "docker",
    "kubernetes",
    "terraform",
    "ci/cd",
    "git",
    "github",
    "gitlab",

    # Web & API
    "fastapi",
    "flask",
    "django",
    "react",
    "node.js",
    "rest api",
    "graphql",
    "html",
    "css",

    # Soft Skills & Methodology
    "communication",
    "teamwork",
    "problem solving",
    "critical thinking",
    "agile",
    "scrum",
    "jira",
    "confluence",
    "stakeholder management",
    "presentation skills",
    "storytelling with data",

    # Tools & Productivity
    "jupyter",
    "google colab",
    "vs code",
    "git",
    "linux",
    "microsoft office",
    "google sheets",
    "notion",
    "slack",
]